<?php
/**
 * Professor card — landscape portrait with name overlay.
 * The .professor-card markup is also generated by the search
 * overlay JS, so the class names must stay stable.
 */
?>
<li class="professor-card__list-item reveal-up">
  <a class="professor-card" href="<?php the_permalink(); ?>">
    <?php if (has_post_thumbnail()) {
      the_post_thumbnail('professorLandscape', array('class' => 'professor-card__image', 'alt' => get_the_title()));
    } else { ?>
      <img class="professor-card__image" src="<?php echo esc_url(get_theme_file_uri('/images/banner-about.jpg')); ?>" alt="<?php the_title_attribute(); ?>">
    <?php } ?>
    <span class="professor-card__name"><?php the_title(); ?></span>
  </a>
</li>
